### ISSUE TITLE
Error when trying to execute ./run_add_demo_entries.bash

### ISSUE THREAD

**Issue by srujanamanvi** [p4lang/p4factory#123]
Running the command ./run_add_demo_entries.bash gives me the following error:
ImportError: No module named p4_pd_rpc.simple_router
ImportError: No module named p4_pd_rpc.simple_router
ImportError: No module named p4_pd_rpc.simple_router
ImportError: No module named p4_pd_rpc.simple_router

**Comment by qq995002966** [comment]
I have the same kind but not the same problem,`when excute ./run_add_demo_entries.bash`,I get the following error:
```
 handlers could be found for logger "thrift.transport.TSocket"
Traceback (most recent call last):
  File "../../cli/pd_cli.py", line 677, in <module>
    main(sys.argv[1:])
  File "../../cli/pd_cli.py", line 665, in main
    pd_cli = PdCli(p4_name, thrift_client_module, thrift_server, port)
  File "../../cli/pd_cli.py", line 35, in __init__
    self._thrift_client = pd_thrift_client.ThriftClient(self._module,
thrift_server, port, self._p4_name)
  File "/home/mininet/documents/p4factory/cli/pd_thrift_client.py", line 55, in
__init__
    self.setup(hostname, port)
  File "/home/mininet/documents/p4factory/cli/pd_thrift_client.py", line 77, in
setup
    self._transport.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py",
line 152, in open
    return self.__trans.open()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py",
line 113, in open
    raise TTransportException(TTransportException.NOT_OPEN, msg)
thrift.transport.TTransport.TTransportException: Could not connect to any of
[('127.0.0.1', 22222), ('127.0.0.1', 22222)]
```

Can someone please help,thk.

**Comment by qq995002966** [comment]
I have solved the problem.If you encountered the similiar problem you could try:
> ` sudo mn -c `
> `sudo killall behavioral-model `
> `redis-cli FLUSHALL`

to clean the trash Mininet created when it crash unnormally.

**Comment by Wasdns** [comment]
Hi, @srujanamanvi 

Please execute `make` in this directory before starting the mininet topo.

Regards,
Chen.
