### ISSUE TITLE
Error on running the python script int_ref_topology.py

### ISSUE THREAD

**Issue by dannyxx001** [p4lang/p4factory#131]
Hi,

We got the following error while running the test python script int_ref_topology.py 

Traceback (most recent call last):
  File "./int_ref_topology.py", line 107, in <module>
    run_cfg()
  File "./int_ref_topology.py", line 83, in run_cfg
    net = mgr.setupAndStartNetwork()
  File "/home/dannyxx001/git_repositories/p4lang/p4factory/mininet/int_cfg.py", line 114, in setupAndStartNetwork
    self.addLinks()
  File "/home/dannyxx001/git_repositories/p4lang/p4factory/mininet/int_cfg.py", line 169, in addLinks
    self.net.addLink( n1, n2, port1 = l.port1 + 1, fast=False, bw=5)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 366, in addLink
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 534, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 424, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 468, in makeIntfPair
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 194, in makeIntfPair
Exception: Error creating interface pair (leaf1-eth1,h1-eth0): RTNETLINK answers: No such process

Could you please check this issue.

Thanks,
Danny Ye

**Comment by dannyxx001** [comment]
Excuse me, I found a solution that I should type "sudo make develop" in mininet repository to create symbolic links from /usr/python/... to my source tree. So it was the problem that I was negligent to do this. Sorry for bothering you. Thanks.
