### ISSUE TITLE
INT: Unable to run the docker image for mininet-spine1

### ISSUE THREAD

**Issue by Muthuramane** [p4lang/p4factory#175]
Hi All,

I am try to run the apps/int but it had problem while running the docker.

parallels@ubuntu:~/p4lang/p4factory/mininet$ sudo ./int_ref_topology.py 
[sudo] password for parallels: 
['docker', 'run', '-ti', '--rm', '--privileged=true', '--hostname=spine1', '--name=mininet-spine1', '-p', '26002:9091', '-e', 'DISPLAY', '-v', '/tmp/.X11-unix:/tmp/.X11-unix', '-v', '/home/parallels/p4lang/p4factory/mininet/configs/spine1/l3_int_ref_topo:/configs', 'p4dockerswitch', '/p4factory/tools/start.sh']
Traceback (most recent call last):
  File "./int_ref_topology.py", line 107, in <module>
    run_cfg()
  File "./int_ref_topology.py", line 83, in run_cfg
    net = mgr.setupAndStartNetwork()
  File "/home/parallels/p4lang/p4factory/mininet/int_cfg.py", line 113, in setupAndStartNetwork
    self.addSwitches()
  File "/home/parallels/p4lang/p4factory/mininet/int_cfg.py", line 147, in addSwitches
    pps = s.pps, qdepth = s.qdepth)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 240, in addSwitch
  File "/home/parallels/p4lang/p4factory/mininet/p4_mininet.py", line 148, in __init__
    Switch.__init__( self, name, **kwargs )
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 855, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 106, in __init__
  File "/home/parallels/p4lang/p4factory/mininet/p4_mininet.py", line 277, in startShell
    self.pid = int(ps_out[0])
ValueError: invalid literal for int() with base 10: ''

I ran the same command by manually

sudo docker run -ti --rm --privileged=true --hostname=spine1 --name=mininet-spine1 -p 26002:9091  -e  DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/parallels/p4lang/p4factory/mininet/configs/spine1/l3_int_ref_topo:/configs p4dockerswitch /p4factory/tools/start.sh
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/p4factory/tools/start.sh\\\": stat /p4factory/tools/start.sh: no such file or directory\"\n".

The file start.sh is missing under the directory p4factory/tools/start.sh.

Please, any one know about this issue

**Comment by herlenashavi** [comment]
Hi,
The mininet scripts for INT will be hosted in a new repo. In the meanwhile, I recommend you to use [NTF](https://github.com/p4lang/ntf/tree/c68deaa2dbcba253527906ed0d55ae223b332fb9/apps/int) to run the mininet scripts for INT.

Thanks

**Comment by herlenashavi** [comment]
INT example in p4factory has been fixed. Please refer [link](https://github.com/p4lang/p4factory/tree/master/apps/int).

Thanks

**Comment by Muthuramane** [comment]
Thanks @herlenashavi .

The problem was resolved.

**Comment by ersuneetsingh** [comment]
Hi, 
I am getting the following error, could you please give any suggestions:
Adding switch spine1
Adding switch spine2
Adding switch leaf1
Adding switch leaf2
Waiting 10 seconds for switches to intialize...
INT Config  spine1
Traceback (most recent call last):
  File "./int_ref_topology.py", line 131, in <module>
    run_cfg(model_dir)
  File "./int_ref_topology.py", line 91, in run_cfg
    net = mgr.setupAndStartNetwork()
  File "/home/suneet/Desktop/p4factory/mininet/int_cfg.py", line 148, in setupAndStartNetwork
    self.configSwitches()
  File "/home/suneet/Desktop/p4factory/mininet/int_cfg.py", line 238, in configSwitches
    self.configSwitch(s)
  File "/home/suneet/Desktop/p4factory/mininet/int_cfg.py", line 252, in configSwitch
    client.switcht_api_init( device )
  File "/home/suneet/Desktop/p4factory/submodules/switch/switchapi/switch_api_thrift/switch_api_rpc.py", line 1565, in switcht_api_init
    return self.recv_switcht_api_init()
  File "/home/suneet/Desktop/p4factory/submodules/switch/switchapi/switch_api_thrift/switch_api_rpc.py", line 1577, in recv_switcht_api_init
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 162, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes

**Comment by jafingerhut** [comment]
Note that the top level README of this project points out that it is deprecated, and recommends looking at p4lang/tutorials instead, which has several people working on it, and thus you are more likely to get help with problems.  It is fairly unlikely someone will be interested in helping you debug issues with the code in this repository.

**Comment by ersuneetsingh** [comment]
@jafingerhut 
Thank you for your suggestions. I build the switch docker image and  the VXLAN-GPE driver again, now everything is working perfectly.

Thank you.
