### ISSUE TITLE
target switch make bm error 

### ISSUE THREAD

**Issue by jiangcheng1** [p4lang/p4factory#176]
root@p4-OSNBA:/home/jiangcheng/p4factory/targets/switch# make bm
/home/jiangcheng/p4factory/submodules/p4c-behavioral/p4c_bm/shell.py /home/jiangcheng/p4factory/submodules/switch/p4src/switch.p4 --gen-dir=/home/jiangcheng/p4factory/targets/switch/build//bm/ --thrift --public-inc-path=/home/jiangcheng/p4factory/targets/switch/build//inc/p4_sim --p4-prefix=dc -DRATE_LIMITING
parsing successful
Semantic warning: Parameter fabric_mgid of action set_fabric_multicast defined in file /home/jiangcheng/p4factory/submodules/switch/p4src/fabric.p4 at line 211 is not being used and will be removed
Semantic warning: header type 'ieee802_1ah_t' is not reachable and will be removed
Semantic warning: header type 'ipsec_esp_t' is not reachable and will be removed
Semantic warning: header type 'ipsec_ah_t' is not reachable and will be removed
Semantic warning: header type 'arp_rarp_t' is not reachable and will be removed
Semantic warning: header type 'arp_rarp_ipv4_t' is not reachable and will be removed
Semantic warning: header type 'genv_opt_A_t' is not reachable and will be removed
Semantic warning: header type 'genv_opt_B_t' is not reachable and will be removed
Semantic warning: header type 'genv_opt_C_t' is not reachable and will be removed
Semantic warning: header type 'sflow_sample_cpu_t' is not reachable and will be removed
Semantic warning: parser function 'parse_roce' is not reachable and will be removed
Semantic warning: parser function 'parse_fcoe' is not reachable and will be removed
Semantic warning: parser function 'parse_vpls' is not reachable and will be removed
Semantic warning: parser function 'parse_pw' is not reachable and will be removed
Semantic warning: parser function 'parse_udp_v6' is not reachable and will be removed
Semantic warning: parser function 'parse_gre_v6' is not reachable and will be removed
Semantic warning: parser function 'parse_roce_v2' is not reachable and will be removed
Semantic warning: parser function 'parse_sctp' is not reachable and will be removed
Semantic warning: header instance 'outer_udp' is not reachable and will be removed
Semantic warning: header instance 'eompls' is not reachable and will be removed
Semantic warning: parser function 'parse_nsh' is not reachable and will be removed
Semantic warning: parser function 'parse_lisp' is not reachable and will be removed
Semantic warning: parser function 'parse_inner_sctp' is not reachable and will be removed
Semantic warning: parser function 'parse_trill' is not reachable and will be removed
Semantic warning: parser function 'parse_vntag' is not reachable and will be removed
Semantic warning: parser function 'parse_bfd' is not reachable and will be removed
Semantic warning: header instance 'sflow_sample' is not reachable and will be removed
Semantic warning: header instance 'sflow_raw_hdr_record' is not reachable and will be removed
Semantic warning: header instance 'global_config_metadata' is not reachable and will be removed
Semantic warning: table 'outer_multicast_rpf' is not reachable and will be removed
Semantic warning: table 'multicast_rpf' is not reachable and will be removed
Semantic warning: control function 'process_mirroring' is not reachable and will be removed
Semantic warning: header type 'eompls_t' is not reachable and will be removed
Semantic warning: header type 'sflow_sample_t' is not reachable and will be removed
Semantic warning: header type 'sflow_raw_hdr_record_t' is not reachable and will be removed
Semantic warning: header instance 'roce' is not reachable and will be removed
Semantic warning: header instance 'fcoe' is not reachable and will be removed
Semantic warning: header instance 'roce_v2' is not reachable and will be removed
Semantic warning: header instance 'sctp' is not reachable and will be removed
Semantic warning: header instance 'nsh' is not reachable and will be removed
Semantic warning: header instance 'nsh_context' is not reachable and will be removed
Semantic warning: header instance 'lisp' is not reachable and will be removed
Semantic warning: header instance 'inner_sctp' is not reachable and will be removed
Semantic warning: header instance 'trill' is not reachable and will be removed
Semantic warning: header instance 'vntag' is not reachable and will be removed
Semantic warning: header instance 'bfd' is not reachable and will be removed
Semantic warning: parser function 'parse_set_prio_max' is not reachable and will be removed
Semantic warning: header type 'global_config_metadata_t' is not reachable and will be removed
Semantic warning: action 'outer_multicast_rpf_check_pass' is not reachable and will be removed
Semantic warning: action 'multicast_rpf_check_pass' is not reachable and will be removed
Semantic warning: action 'multicast_rpf_check_fail' is not reachable and will be removed
Semantic warning: header type 'roce_header_t' is not reachable and will be removed
Semantic warning: header type 'roce_v2_header_t' is not reachable and will be removed
Semantic warning: header type 'fcoe_header_t' is not reachable and will be removed
Semantic warning: header type 'sctp_t' is not reachable and will be removed
Semantic warning: header type 'nsh_t' is not reachable and will be removed
Semantic warning: header type 'nsh_context_t' is not reachable and will be removed
Semantic warning: header type 'trill_t' is not reachable and will be removed
Semantic warning: header type 'lisp_t' is not reachable and will be removed
Semantic warning: header type 'vntag_t' is not reachable and will be removed
Semantic warning: header type 'bfd_t' is not reachable and will be removed
semantic checking successful
Header type standard_metadata_t not byte-aligned, adding padding
Header type ingress_intrinsic_metadata_t not byte-aligned, adding padding
Header type ingress_metadata_t not byte-aligned, adding padding
Header type egress_metadata_t not byte-aligned, adding padding
Header type l2_metadata_t not byte-aligned, adding padding
Header type l3_metadata_t not byte-aligned, adding padding
Header type ipv4_metadata_t not byte-aligned, adding padding
Header type ipv6_metadata_t not byte-aligned, adding padding
Header type tunnel_metadata_t not byte-aligned, adding padding
Header type acl_metadata_t not byte-aligned, adding padding
Header type nat_metadata_t not byte-aligned, adding padding
Header type multicast_metadata_t not byte-aligned, adding padding
Header type nexthop_metadata_t not byte-aligned, adding padding
Header type security_metadata_t not byte-aligned, adding padding
Header type fabric_metadata_t not byte-aligned, adding padding
Header type int_metadata_i2e_t not byte-aligned, adding padding
Header type meter_metadata_t not byte-aligned, adding padding
Header type qos_metadata_t not byte-aligned, adding padding
Generating files in directory /home/jiangcheng/p4factory/targets/switch/build/bm
total phv length (in bytes): 2000
P4_MATCH_RANGE match not yet supported
Traceback (most recent call last):
  File "/home/jiangcheng/p4factory/submodules/p4c-behavioral/p4c_bm/shell.py", line 150, in <module>
    main()
  File "/home/jiangcheng/p4factory/submodules/p4c-behavioral/p4c_bm/shell.py", line 138, in main
    dump_yaml = args.dump_yaml)
  File "/home/jiangcheng/p4factory/submodules/p4c-behavioral/p4c_bm/smart.py", line 1164, in render_dict_create
    render_dict_populate_tables(render_dict, hlir)
  File "/home/jiangcheng/p4factory/submodules/p4c-behavioral/p4c_bm/smart.py", line 661, in render_dict_populate_tables
    assert(False)
AssertionError
make: *** [bm_tenjin_output_oldest] Error 1

**Comment by antoninbas** [comment]
The first version of the behavioral-model (bmv1 / p4c-behavioral) does not support the `range` match type. Therefore, now that switch.p4 leverages the `range` match type, it can no longer be run with bmv1 and we should be completely removing bmv1 from p4lang very soon.
The new version of the behavioral-model (bmv2) does support the `range` match type. The recommended steps to run switch.p4 with bmv2 can be found here: https://github.com/p4lang/switch#running-switch-in-bmv2-without-p4factory
