### ISSUE TITLE
Connection reset by Peer (error 104) - When INT configuring SPINE

### ISSUE THREAD

**Issue by kohilaramesh** [p4lang/p4factory#187]
I am getting the following error when INT configuring spine switches in mininet emulated environment

kohila@kohila-vb:~/p4factory/mininet$ sudo ./int_ref_topology.py --model-dir=$HOME/install
Adding switch spine1
Adding switch spine2
Adding switch leaf1
Adding switch leaf2
Waiting 10 seconds for switches to intialize...
INT Config  spine1
Traceback (most recent call last):
  File "./int_ref_topology.py", line 131, in <module>
    run_cfg(model_dir)
  File "./int_ref_topology.py", line 91, in run_cfg
    net = mgr.setupAndStartNetwork()
  File "/home/kohila/p4factory/mininet/int_cfg.py", line 147, in setupAndStartNetwork
    self.configSwitches()
  File "/home/kohila/p4factory/mininet/int_cfg.py", line 237, in configSwitches
    self.configSwitch(s)
  File "/home/kohila/p4factory/mininet/int_cfg.py", line 251, in configSwitch
    client.switcht_api_init( device )
  File "/home/kohila/p4factory/submodules/switch/switchapi/switch_api_thrift/switch_api_rpc.py", line 1565, in switcht_api_init
    return self.recv_switcht_api_init()
  File "/home/kohila/p4factory/submodules/switch/switchapi/switch_api_thrift/switch_api_rpc.py", line 1577, in recv_switcht_api_init
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 161, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 117, in read
    buff = self.handle.recv(sz)
socket.error: [Errno 104] Connection reset by peer
kohila@kohila-vb:~/p4factory/mininet$

Anybody have faced similar issue ? Please help me to fix this issue.

Thanks
Kohila

**Comment by gopchandani** [comment]
Yep. Seeing the exact same error. This repo seems to have been abandoned, may have to start digging in here.
 
If you found a fix, please do share.

**Comment by gopchandani** [comment]
Okay, this required me to ensure that the switch driver (a file called: bmswitchp4_drivers) is correctly built and placed in the ~/install location. You would need to rebuild the switch docker after compilation.

**Comment by MehmedGIT** [comment]
Hi gopchandani,

I am getting the same socket error. I tried to ensure the switch drivers, but I am facing core dump. Can you explain in more detail what have you done to make it work ? I really appreciate any help you can provide.
