### ISSUE TITLE
App INT error:Tsocket read 0 bytes error

### ISSUE THREAD

**Issue by haseebnaseem** [p4lang/p4factory#195]
I get the following error when I run the int topology
Tsocket read 0 bytes
Here's the trace:

'Adding switch spine1
Adding switch spine2
Adding switch leaf1
Adding switch leaf2
Waiting 10 seconds for switches to intialize...
INT Config  spine1
Traceback (most recent call last):
  File "./int_ref_topology.py", line 131, in <module>
    run_cfg(model_dir)
  File "./int_ref_topology.py", line 91, in run_cfg
    net = mgr.setupAndStartNetwork()
  File "/home/haseeb/p4factory/mininet/int_cfg.py", line 147, in setupAndStartNetwork
    self.configSwitches()
  File "/home/haseeb/p4factory/mininet/int_cfg.py", line 237, in configSwitches
    self.configSwitch(s)
  File "/home/haseeb/p4factory/mininet/int_cfg.py", line 251, in configSwitch
    client.switcht_api_init( device )
  File "/home/haseeb/p4factory/submodules/switch/switchapi/switch_api_thrift/switch_api_rpc.py", line 1565, in switcht_api_init
    return self.recv_switcht_api_init()
  File "/home/haseeb/p4factory/submodules/switch/switchapi/switch_api_thrift/switch_api_rpc.py", line 1577, in recv_switcht_api_init
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 161, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 132, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes`

**Comment by ersuneetsingh** [comment]
hey, 
I am facing the same problem, could anyone give any suggestion to resolve this problem ?

**Comment by jafingerhut** [comment]
Note that the top level README of this project points out that it is deprecated, and recommends looking at p4lang/tutorials instead, which has several people working on it, and thus you are more likely to get help with problems.  It is fairly unlikely someone will be interested in helping you debug issues with the code in this repository.
